In [153]:
#Gauss Jordan Elimination with n x n matrices 

import numpy as np


A = np.array([[1.0,4.3,2,1,5.6],[3.2,0,1,4,5.0],[1.0,3,2,2,5.1],
              [4.0,1,5,7,13],[4,2,1,2,5.0]])
B = np.array([1.0,2.0,3.0,4.0,5.0])
             
print(A,B,'^T','\n')
for i in range(len(A)-1):          # LOWER TRIANGLE gets zeros
    for j in range(len(A)):
        if j > i:
            k = (A[j][i]/A[i][i])
            A[j] = A[j] - k*A[i]
            B[j] = B[j] - k*B[i]

print(A, B,'^T','\n')
reverse = list(range(len(A)))[::-1]



for m in reverse:                 #Upper Triangle gets zeros (Diagonal intact)
    for n in reverse:
        if m > n:
            k = (A[n][m]/A[m][m])
            A[n] = A[n] - k*A[m]
            B[n] = B[n] - k*B[m]
            
print(A,B,'^T','\n')
for p in range(len(A)):
    print(f'x{p} = {B[p]/A[p][p]}')

[[ 1.   4.3  2.   1.   5.6]
 [ 3.2  0.   1.   4.   5. ]
 [ 1.   3.   2.   2.   5.1]
 [ 4.   1.   5.   7.  13. ]
 [ 4.   2.   1.   2.   5. ]] [1. 2. 3. 4. 5.] ^T 

[[  1.           4.3          2.           1.           5.6       ]
 [  0.         -13.76        -5.4          0.8        -12.92      ]
 [  0.           0.           0.51017442   0.9244186    0.72063953]
 [  0.           0.           0.          -4.02564103   1.06837607]
 [  0.           0.           0.           0.          -1.93375796]] [  1.          -1.2          2.11337209 -12.4957265    9.74309979] ^T 

[[  1.           0.           0.           0.           0.        ]
 [  0.         -13.76         0.           0.           0.        ]
 [  0.           0.           0.51017442   0.           0.        ]
 [  0.           0.           0.          -4.02564103   0.        ]
 [  0.           0.           0.           0.          -1.93375796]] [  3.77086078 -24.19733568   4.11093333  -7.11279086   9.74309979] ^T 

x0 = 3.7708